import Image from 'next/image';
import Link from 'next/link'
import React, { useEffect } from 'react'
import photo from '../../assets/photo/index'

function PhotoAnime() {
  return (
    <div className='h-[25rem] rounded-full w-[25rem] flex flex-col flex-wrap staggering-grid-demo '>
      <Image
        src={photo.a0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.a1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.a2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.a3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.a4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.a5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.a6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.a7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.a8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.a9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.b0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.b1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.b2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.b3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.b4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.b5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.b6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.b7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.b8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.b9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.c0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.c1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.c2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.c3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.c4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.c5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.c6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.c7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.c8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.c9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.d0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.d1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.d2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.d3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.d4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.d5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.d6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.d7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.d8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.d9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.f0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.f1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.f2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.f3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.f4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.f5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.f6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.f7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.f8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.f9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.g0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.g1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.g2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.g3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.g4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.g5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.g6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.g7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.g8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.g9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.h0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.h1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.h2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.h3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.h4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.h5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.h6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.h7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.h8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.h9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.i0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.i1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.i2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.i3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.i4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.i5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.i6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.i7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.i8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.i9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.j0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.j1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.j2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.j3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.j4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.j5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.j6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.j7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.j8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.j9} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.k0} 
        height={40}
        width={40}
        className="el"
        />
        <Image
          src={photo.k1} 
          height={40}
          width={40}
          className="el"
          />
      <Image
        src={photo.k2} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.k3} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.k4} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.k5} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.k6} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.k7} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.k8} 
        height={40}
        width={40}
        className="el"
        />
      <Image
        src={photo.k9} 
        height={40}
        width={40}
        className="el"
        />
       
    </div>
  )
}

export default PhotoAnime